name = "MiniMax 2.5"
attachment = false
reasoning = true
tool_call = true
temperature = true
open_weights = false

[cost]
input = 0
output = 0

[limit]
context = 204_800
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
