name = "Qwen3 Coder Next"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true

[cost]
input = 0
output = 0

[limit]
context = 256_000
output = 64_000

[modalities]
input = ["text"]
output = ["text"]
